# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: syringe-server
    main: cmd/server/main.go
    binary: syringeserver
    env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
      - darwin_arm64

  - id: syringe-cli
    main: cmd/cli/main.go
    binary: syringe
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_arm64

archives:
  - id: syringe-cli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - syringe-cli

  - id: syringe-server
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - syringe-server

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
