version: "3"
services:
  syringeserver:
    build:
      context: .
      args:
        # (required) The version of syringe server to use.
        - VERSION=0.0.13
    environment:
      # (optional) Path inside container to server's private key. If it doesn't exist, a new key will be created at this path.
      - HOST_KEY_PATH=/home/syringe/.ssh/id_ed25519

      # (optional) Path inside container of mountpoint to data volume where to create databases. Required if volume mounted.
      # - DATA_PATH=/home/syringe/data

      # (required) Username to use for app database.
      - DB_USER=admin

      # (required) Password to use for app database.
      - DB_PASSWORD=p4ssw0rd

    ports:
      # (required) Server always runs on port 22. Expose it on whatever host port you need it on.
      - 2222:22
    volumes:
      # (optional) Volume to mount for databases. If you don't provide this, you'll lose your data every time.
      # - /syringedata:/home/syringe/data

      # (optional) Volume to mount for host key. If you don't provide it, a new key will be generated every time.
      - /home/nixpig/projects/syringe.sh/server/.ssh/id_ed25519:/home/syringe/.ssh/id_ed25519
# (optional) Volume to use when mounting a volume to store databases.
# volumes:
#   syringedata:
