version: "3"
services:
  syringeserver:
    build:
      context: .
      args:
        # (required) The version of syringe server to use.
        - VERSION=0.0.16

    environment:
      # (optional) Path inside container of mountpoint to data volume where to create databases.
      - DATA_PATH=/data

      # (optional) Path inside container to server's private key. If it doesn't exist, a new key will be created at this path.
      - HOST_KEY_PATH=/hostkey

      # (required) Username to use for app database.
      - DB_USER=admin

      # (required) Password to use for app database.
      - DB_PASSWORD=p4ssw0rd

    ports:
      # (required) Server always runs on port 22. Expose it on whatever host port you need it on.
      - 23234:22

    volumes:
      # (optional) Volume to mount for databases. If you don't provide this, you'll lose your data every time.
      - ./syringedata:/data:rw

      # (optional) Volume to mount for host key. If you don't provide it, a new key will be generated every time.
      - .ssh/id_ed25519:/hostkey:ro
