name: build

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual trigger"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Audit
        run: make audit

      - name: Install dependecies
        run: go mod download

      - name: Run unit tests with coverage
        run: make coverage

      - name: Upload coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          make coveralls

      - name: Build server
        run: make server

      - name: Build cli
        run: make cli

