name: release

on:
  push:
    tags:
      - 0.**

  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: go run github.com/goreleaser/goreleaser/v2@latest release
